sched/tune: Remove leftover instances of allow_attach
Fix:

kernel/sched/tune.c:718:2: error:
	unknown field allow_attach specified in initializer
kernel/cpuset.c:2087:2: error:
	unknown field 'allow_attach' specified in initializer

Fixes: e78f134a78a0 ("CHROMIUM: remove Android's cgroup generic permissions checks")

BUG=chrome-os-partner:58667
TEST=build/boot on kevin

Change-Id: Ie524350ffc6158f3182d90095cca502e58b6f197
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 7bb5218b77d0aef456634625fff7909f88b4f70
 from android-msm/android-4.4.y)
Signed-off-by: Sonny Rao <sonnyrao@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/420095
Commit-Ready: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Signed-off-by: mydongistiny <jaysonedson@gmail.com>